Regression model from skeleton
IGNF/lidro pull request #10
Opened 2024-08-09 14:05 UTC by mdupaysign

Etape finale de création des points virtuels sur l'ensemble du chantier. 
Dans une prochaine versio, il faudra ramener ces points virtuels à la dalle. 

/ ! \ Lire le README pour bien comprendre l'enchainement des traitements

2024-08-13 14:51 UTC, leavauchier requested changes

2024-08-13 14:51 UTC, leavauchier commented on README.md
> +* 1- création automatique du tronçon hydrographique ("Squelette hydrographique", soit les tronçons hydrographiques dans la BD Unis) à partir de l'emprise du masque hydrographique "écoulement".
Question pour la suite : il y a moyen de rendre ça possible de faire la requête depuis la BD Topo pour le commun des mortels ?

2024-08-13 14:51 UTC, leavauchier commented on README.md
> +Pour les cours d'eaux supérieurs à 150 m de long :
typo : 
```suggestion
Pour les cours d'eau supérieurs à 150 m de long :
```

2024-08-13 14:51 UTC, leavauchier commented on README.md
> +* 4- Générer un modèle de régression linéaire afin de générer tous les N mètres une valeur d'altitude le long du squelette de cette rivière. Les différents Z le long des squelettes HYDRO doivent assu
typo : 
```suggestion
* 4- Générer un modèle de régression linéaire afin de générer tous les N mètres une valeur d'altitude le long du squelette de cette rivière. Les différents Z le long des squelettes HYDRO doivent assurer l'écoulement. Il est important de noter que tous les 50 mètres semble une valeur correcte. Cette valeur s'explique en raison de la précision planimétrique et altimétrique des données LIDAR ET que les rivières françaises correspondent à des cours d’eau naturels dont la pente est inférieure à 1%. 
```

2024-08-13 14:51 UTC, leavauchier commented on README.md
> +/ ! \ Pour les cours d'eaux inférieurs à 150 m de long, le modèle de régression linéaire ne fonctionne pas. La valeur du premier quartile sera calculée sur l'ensemble des points d'altitudes du LIDAR
typo : 
```suggestion
/ ! \ Pour les cours d'eau inférieurs à 150 m de long, le modèle de régression linéaire ne fonctionne pas. La valeur du premier quartile sera calculée sur l'ensemble des points d'altitudes du LIDAR "SOL" (étape 2) et affectée pour ces entités hydrographiques (< 150m de long) : aplanissement. 
```

2024-08-13 14:51 UTC, leavauchier commented on README.md
> +  * Création des points virtuels 2D espacés selon une grille régulière espacés tous les N mètres (paramètrables) à l'intérieur du masque hydrographique "écoulement"
typo : 
```suggestion
  * Création des points virtuels 2D espacés selon une grille régulière tous les N mètres (paramétrable) à l'intérieur du masque hydrographique "écoulement"
```

2024-08-13 14:51 UTC, leavauchier commented on README.md
> +  * Création des points virtuels 2D espacés selon une grille régulière espacés tous les N mètres (paramètrables) à l'intérieur du masque hydrographique "écoulement"
en fait au lieu de mettre "paramétrable" à plein d'endroits, ce serait peut-être plus simple de mettre une note au début du type :

```
**Note** : la plupart des valeurs décrites dans la suite sont des valeurs par défaut modifiables dans le fichier xxx
```

2024-08-13 14:51 UTC, leavauchier commented on README.md
>  * 1- Extraction et enregistrement temporairement des points LIDAR classés en « Sol » et « Eau » présents potentiellement à la limite +1 mètre des berges. Pour cela, on s'appuie sur 'emprise du masque
typo : 
```suggestion
* 1- Extraction et enregistrement temporairement des points LIDAR classés en « Sol » et « Eau » présents potentiellement à la limite + 1 mètre des berges. Pour cela, on s'appuie sur l'emprise du masque hydrographique "surface plane" apparaier, contrôler et corriger par la "production" (SV3D) en amont (étape manuelle). a noter que pur le secteur maritime (Mer), il faut exclure la classe « 9 » (eau) afin d’éviter de mesurer les vagues.
```

2024-08-13 14:51 UTC, leavauchier commented on README.md
> +A. Tester sur un dossier contenant plusieurs dalles LIDAR pour créer des points tous les N mètres le long du squelette hydrographique, et réccupérer les N plus proches voisins points LIDAR "SOL"
pour passer à la ligne dans le rendu, il faut ajouter un saut de ligne : 
```suggestion
* 4- Création des points virtuels

A. Tester sur un dossier contenant plusieurs dalles LIDAR pour créer des points tous les N mètres le long du squelette hydrographique, et réccupérer les N plus proches voisins points LIDAR "SOL"
```

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/pointcloud/convert_geodataframe_to_las.py
> +            "classification": np.full(len(grid_with_z), 68, dtype=np.uint8),  # Add classification of 68
Vu que ça va changer à terme (et qu'on n'est pas à l'abri que ça arrive bientôt), je pense que c'est malin de rendre cette classification paramétrable dans le fichier de config

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/pointcloud/convert_geodataframe_to_las.py
> +    las.classification = las_data["classification"].values
j'ai l'impression que tu peux supprimer des étapes intermédiaires vu que ton entrée est déjà une GeoDataFrame (tu fais déjà la concaténation en dehors si j'ai bien compris) : 
[ça vaut le coup de revérifier ce que j'ai écrit ici, c'est juste un brouillon]

```suggestion
def geodataframe_to_las(virtual_points: gpd.GeoDataFrame, output_dir: str, crs: str):
    """This function convert virtual points (GeoDataframe) to LIDAR points with classification (66) for virtual points

    Args:
        virtual_points (gpd.GeoDataFrame): A GeoDataFrame containing virtuals points from Mask Hydro
        output_dir (str): folder to output LAS
        crs (str): a pyproj CRS object used to create the output GeoJSON file
    """

    # Create a LAS file with laspy
    header = laspy.LasHeader(point_format=6, version="1.4")

    # Create a LAS file with laspy and add the VLR for CRS
    las = laspy.LasData(header)
    las.x = grid_with_z.geometry.x.values
    las.y =grid_with_z.geometry.y.values
    las.z = grid_with_z.geometry.z.values
    las.classification = np.full(len(grid_with_z), 68, dtype=np.uint8),  # Add classification of 68
```

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/pointcloud/convert_geodataframe_to_las.py
> +    output_las = os.path.join(output_dir, "virtual_points.las")
utilise plutôt du laz, ça vaut le coup de compresser

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/vectors/apply_Z_from_grid.py
> +    # Calculate curvilinear abscises for all points of the grid
tu peux rajouter que si les points ne sont pas sur la ligne, ils sont projetés sur la ligne avec cette fonction stp ?

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/vectors/apply_Z_from_grid.py
> +def calculate_grid_z_for_flattening(
pas sûre de voir la différence entre cette fonctione t les lignes 26 à 31 de ce même fichier, c'est un doublon ?

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/vectors/create_grid_2D_inside_maskhydro.py
> +        spacing (float): Spacing between the grid points in meters. The default value is 1 meter.
il y a une incohérence avec la signature de la fonction (tu n'as aps mis de valeur par défaut)

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/vectors/extract_points_around_skeleton.py
> +        df_points_z["points_knn"] = df_points_z["points_knn"].apply(
à première vue ça parait pas idéal de passer par une chaîne de caractères en limitant le nombre de chiffres après la virgule mais j'ai l'impression que ça correspond ua problème dont tu m'as parlé avec l'écriture en geojson

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/vectors/extract_points_around_skeleton.py
> +        df_points_z["points_knn"] = df_points_z["points_knn"].apply(
Ce qui m'embête surtout, c'est que tu doives utiliser ça dans geopandas, qui à mon souvenir gère plutôt mal des chaines de caractères

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/vectors/flatten_river.py
> +        logging.warning("For little river : error Z quartile")
proposition d'erreur plus explicite : 
```suggestion
        logging.warning("For little river: no neighbor found to calculate Z quartile: set Z to 0")
```

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/vectors/intersect_points_by_line.py
> +def apply_buffers_to_geometry(line: gpd.GeoDataFrame, buffer: float) -> Polygon:
j'ai pas l'impression qu'il y a besoin d'une fonction spécifique ici vu qu'elle ne fait qu'une ligne

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/vectors/intersect_points_by_line.py
> +    # Apply buffer (2 meters by default) from Mask Hydro
ton commentaire dit que tu as un buffer de 2 mètres, et ton code 0.1 : est-ce que ça vaut le coup de rendre la taille du buffer paramétrable ou cette partie reste fixe ?

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/vectors/las_around_point.py
> +        List : Result {'geometry': Point 2D on skeleton, 'points_knn': List of LIDAR points from}
apparemment tu n'as aps fini ta phrase

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/vectors/intersect_points_by_line.py
> +def return_points_by_line(points: gpd.GeoDataFrame, line: gpd.GeoDataFrame) -> gpd.GeoDataFrame:
là il s'agit de points qui sont sur ton squelette ou déjà des points de ta grille ?

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/vectors/mask_hydro_with_buffer.py
> +    # gdf_buffer = gdf.buffer(0.1, cap_style=CAP_STYLE.square).difference(
code mort à enlever ?

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/vectors/run_create_virtual_points.py
> +    # Check if points GeoDataFrame is empty or
ta phrase n'a pas l'air finie

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/vectors/run_create_virtual_points.py
> +        if river_length > 150:
t'as rendu plein de paramètres réglables, je pense que celui-ci peut l'être aussi

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/vectors/run_create_virtual_points.py
> +                    f"Save masks_without_points because of linear regression is impossible: {output_mask_hydro_error}"
typo : 
```suggestion
                    f"Save masks_without_points because linear regression is impossible: {output_mask_hydro_error}"
```

2024-08-13 14:51 UTC, leavauchier commented on lidro/create_virtual_point/vectors/run_create_virtual_points.py
> +        if river_length < 150:
il vaut mieux mettre un `else` ici : 
là tu as les cas `river_length > 150` et `river_length < 150` masi si `river_length == 150` il ne se passe rien (il va forcément y avoir un moment où ça arrive comme on traite de grands volumes de données)

2024-08-13 14:51 UTC, leavauchier commented on lidro/main_create_virtual_point.py
> +    s = config.virtual_point.vector.s
`s` ? ça correspond à quoi ? est-ce que tu peux avoir un nom de variable plus explicite stp ?

2024-08-13 14:51 UTC, leavauchier commented on lidro/main_create_virtual_point.py
> +        return [[round(coord, 8) for coord in point] for point in points_knn]
poruquoi 8 décimales ? si c'est des coordonnées en mètres, le millimètre c'est déjà pas mal :)

2024-08-13 14:51 UTC, leavauchier commented on lidro/main_extract_points_from_skeleton.py
> +""" Main script for calculate Mask HYDRO 1
tu peux mettre à jour stp ?

2024-08-13 14:51 UTC, leavauchier commented on lidro/main_create_virtual_point.py
> +        logging.error("No valid data found in points_clip for processing.")
ça va être obscure comme erreur, est-ce que tu peux expliciter ce à quoi correspond points_clip stp ?

2024-08-13 14:51 UTC, leavauchier commented on scripts/example_create_mask_default.sh
> +#io.mask_generation.raster.dilatation_size=3 \ #size for dilatation
code mort ?

2024-08-13 14:51 UTC, leavauchier commented on scripts/example_create_virtual_point_by_tile.sh
> +#io.virtual_point.vector.s=0.5 \ #Spacing between the grid points in meters
code mort ?

2024-08-13 14:51 UTC, leavauchier commented on scripts/example_create_virtual_point_default.sh
> +#io.virtual_point.vector.s=0.5 \ #Spacing between the grid points in meters
code mort ?

2024-08-13 14:51 UTC, leavauchier commented on scripts/example_extract_points_around_skeleton_default.sh
> +#io.virtual_point.filter.keep_neighbors_classes=[2, 9] \ #Keep ground and water pointclouds between Hydro Mask and Hydro Mask buffer
code mort ?

2024-08-13 14:51 UTC, leavauchier commented on scripts/example_merge_mask_default.sh
> +#io.mask_generation.vector.buffer_positive=1 \ #Parameters for buffer
code mort ?

2024-08-22 07:14 UTC, leavauchier requested changes
Revue partielle

2024-08-22 07:14 UTC, leavauchier commented on lidro/create_virtual_point/vectors/flatten_river.py
> +    points_knn_values = gdf_points["points_knn"].dropna().values
tu fais déjà un `dropna` dans `return_points_by_line`, quelle est la différence ici ? Et j'ai l'impression que si c'est 2 étapes différentes, tu peux ajouter celle-ci dans `return_points_by_line`.
`reutrn_points_by_line` peut même carrément renvoyer `points_knn_values si tu ne te sers pas directement de gdf_points.

2024-08-22 07:14 UTC, leavauchier commented on lidro/main_create_virtual_point.py
> +    s = config.virtual_point.vector.s
c'était bien ton ancienne version avec `input_dir_points_skeleton` au lieu de `input_dir_point_skeketon` (vu que tu as plusieurs points). 
Mon problème est plutôt avec ta variable `s` dans `s = config.virtual_point.vector.s`, ce n'est pas explicite (en général il est conseillé d'éviter les variables à 1 lettre). Si j'ai bien compris, c'est l'espacement entre les points de la grille, donc tu peux mettre quelque chose comme `virtual_points_spacing` ou `points_grid_spacing` (ou juste `spacing` si ça te parait trop long)

2024-08-22 07:14 UTC, leavauchier commented on test/test_main_create_virtual_point.py
> -def test_main_lidro_fail_no_input_dir():
pourquoi enlever ces tests ?

2024-08-22 07:14 UTC, leavauchier commented on configs/configs_lidro.yaml
> +    # Spacing between the grid points in meters by default "0.5"
à mon avis, l'espacement des points sur la grille, et en général ce qui concerne la génération de cette grille de points peut être dans autre catégorie que `vector` qui a l'air de correspondre plus à la création des points le long du squelette. Sinon c'est peut-être un problème de noms de cette catégorie (le fait de créer des points sur une grille ne me semble pas avoir de sens dans une partie parlant de vecteurs)

2024-08-27 15:06 UTC, mdupaysign commented
Correction des remarques @leavauchier

2024-08-27 15:20 UTC, mdupaysign commented on lidro/create_virtual_point/pointcloud/convert_geodataframe_to_las.py
> +    output_las = os.path.join(output_dir, "virtual_points.las")
review [9a97749](https://github.com/IGNF/lidro/pull/10/commits/9a97749fdff89579589f421bfe27c6e2524bf28f)

2024-08-27 15:21 UTC, mdupaysign commented on lidro/create_virtual_point/pointcloud/convert_geodataframe_to_las.py
> +    las.classification = las_data["classification"].values
review : [b62bc00](https://github.com/IGNF/lidro/pull/10/commits/b62bc006b89e62d24708c39c2af3b8f525d2f7ce)

2024-09-03 13:30 UTC, leavauchier requested changes

2024-09-03 13:30 UTC, leavauchier commented on lidro/create_virtual_point/vectors/create_grid_2D_inside_maskhydro.py
> +def generate_grid_from_geojson(mask_hydro: gpd.GeoDataFrame, spacing=0.5, margin=0):
pour garder le typehint, ut peux faire : 
```suggestion
def generate_grid_from_geojson(mask_hydro: gpd.GeoDataFrame, spacing: float = 0.5, margin: float = 0):
```

2024-09-03 13:30 UTC, leavauchier commented on lidro/create_virtual_point/vectors/run_create_virtual_points.py
>          # Calculate the length of the river
ligne 61 :     au lieu de `if not points.empty and not points["points_knn"].isnull().all():`, tu peux mettre juste `else` vu que ça correspond exactement au complémentaire de ton `if points.empty or points["points_knn"].isnull().all():` ligne 51

2024-09-03 13:30 UTC, leavauchier commented on test/vectors/test_create_grid_2D_inside_maskhydro.py
> +    margin = 0  # à marging
typo 
```suggestion
    margin = 0  # no margin
```

2024-09-03 13:30 UTC, leavauchier commented on test/vectors/test_create_grid_2D_inside_maskhydro.py
> +    margin = 0  # à marging
c'est à tester aussi avec une marge (et potentiellement avec d'autres valeurs de `spacing`

2024-09-03 13:30 UTC, leavauchier commented on lidro/main_create_virtual_point.py
> +        gdf_virtual_points = [
j'ai 'limrpeesion que tu tu peux revoir tes commentaires "step 1, step 2, etc. : ici on n'est plus dans la partie "Smooth Z" mais dans la création des points virtuels"

2024-09-03 13:30 UTC, leavauchier commented on lidro/main_create_virtual_point.py
> +            launch_virtual_points_by_section(
c'est à l'intérieur de cette fonction que j'aimerais faire la scission pour pouvoir travailler dalle par dalle :
 dans mon idée il faudrait un "main_create_smoothed_skeleton" qui te renvoie un geojson avec ton squelette final

puis, dans un autre main, pour chaque fichier las, tu prends tout le masque hydro + tout le squelette  et tu génères les points qui sont inclus dans ton las
(en gros, tu ferais seulement la fonction `gdf_grid_with_z = calculate_grid_z_with_model(gdf_grid, line, model)` ou `  gdf_grid_with_z = calculate_grid_z_for_flattening(gdf_grid, line, predicted_z)` selon les cas, et tu pourrais même envisager de n'avoir qu'une seule fonction qui est plus générale et qui marche pour les 2 (en ayant comme `model` une ligne plate dans le cas du flattening)

ça implique principalement d'enregistrer quelle partie du squelette va avec quel masque, mais j'ai l'impression que tu as déjà l'info quelque part.

2024-09-05 16:07 UTC, leavauchier commented on lidro/create_virtual_point/pointcloud/convert_geodataframe_to_las.py
> +    las.classification = las_data["classification"].values
proposition : garder geodataframe + 
```python 
def geodataframe_to_las(virtual_points: List, output_dir: str, crs: str, classes: int):
    """This function convert virtual points (GeoDataframe) to LIDAR points with classification for virtual points

    Args:
        virtual_points (List): A list containing virtuals points by hydrological entity
        output_dir (str): folder to output LAS
        crs (str): a pyproj CRS object used to create the output GeoJSON file
        classes (int): The number of the classe assign those virtual points
    """
    # Combine all virtual points into a single GeoDataFrame
    grid_with_z = pd.concat(virtual_points, ignore_index=True)

    # Create a LAS file with laspy
    header = laspy.LasHeader(point_format=6, version="1.4")

    # Create a LAS file with laspy and add the VLR for CRS
    las = laspy.LasData(header)
    las.x = grid_with_z.geometry.x
    las.y = grid_with_z.geometry.y
    las.z = grid_with_z.geometry.z
    las.classification = classes * np.ones(len(grid_with_z.index))

    # Add CRS information to the VLR
    vlr = laspy.vlrs.known.WktCoordinateSystemVlr(crs.to_wkt())
    las.vlrs.append(vlr)

    # Save the LAS file
    output_laz = os.path.join(output_dir, "virtual_points.laz")
    with laspy.open(output_laz, mode="w", header=las.header, do_compress=True) as writer:
        writer.write_points(las.points)

    logging.info(f"Virtual points LAS file saved to {output_laz}")
```

2024-09-09 10:45 UTC, gliegard commented on images/chaine_traitement_lidro.jpg
`cours` au lieu de `cour` dans la partie 3.A

2024-09-12 08:15 UTC, gliegard commented on lidro/main_create_virtual_point.py
> +            launch_virtual_points_by_section(
tu veux faire ça dans une autre PR ?

2024-09-12 09:57 UTC, alavenant approved these changes

2024-09-12 09:57 UTC, merged