Add virtual points to tiles
IGNF/lidro pull request #17
Opened 2024-09-18 15:49 UTC by mdupaysign

ajouter les points virtuels HYDRO à la dalles LIDAR

2024-09-23 09:44 UTC, gliegard requested changes

2024-09-24 14:39 UTC, mdupaysign commented on test/pointcloud/test_add_virtual_points_to_pointcloud.py
> +    assert point_count > 0, "The output LAZ file should contain points."
J'ai modifié en mettant cette condition à la place : ```assert point_count_output > int(point_count_input + point_count_virtual_point), "The output LAZ file should contain points."
```

2024-09-25 12:39 UTC, gliegard commented on lidro/main_clip_virtual_point_by_tile.py
> +    create_geojson_from_laz_files([os.path.join(input_dir, file) for file in os.listdir(input_dir)], json_tiles, crs)
comme suggéré avant que tu fasses un main à part, ce serait plus lisible en deux lignes, avec une variable 
```
laz_files = [os.path.join(input_dir, file) for file in os.listdir(input_dir)]
create_geojson_from_laz_files(laz_files, json_tiles, crs)
```

2024-09-25 12:42 UTC, gliegard commented on test/pointcloud/test_add_virtual_points_to_pointcloud.py
> +    point_count_output = pipeline_output.metadata["metadata"]["readers.las"]["count"]
tu peux faire un petit refactor 
```
def count_points(input_file):
  pipeline_input = pdal.Pipeline() | pdal.Reader.las(input_file, nosrs=True)
  pipeline_input.execute()
  return pipeline_input.metadata["metadata"]["readers.las"]["count"]
```

2024-09-25 12:45 UTC, gliegard commented on lidro/create_virtual_point/pointcloud/auto_tiling_from_las.py
> +            "tile_id": str(int(min_x)) + "_" + str(math.ceil(max_y / 1000) * 1000),
du coup tu utilises des variables globales ?? c'est un vrai problème pour moi, faut qu'on en discute.

2024-09-25 13:11 UTC, gliegard commented on lidro/create_virtual_point/pointcloud/auto_tiling_from_las.py
> +            "tile_id": str(int(min_x)) + "_" + str(math.ceil(max_y / 1000) * 1000),
j'avais mal lu le code décolé

2024-09-27 12:53 UTC, gliegard requested changes

2024-09-27 12:53 UTC, gliegard commented on lidro/create_virtual_point/pointcloud/auto_tiling_from_las.py
> +    Create a GeoJSON from a  count_points(input_file)file.
j'ai l'impression qu'il y a une erreur dans ce commentaire : count_points(input_file)

2024-09-27 13:24 UTC, mdupaysign commented on lidro/create_virtual_point/pointcloud/auto_tiling_from_las.py
> +    Create a GeoJSON from a  count_points(input_file)file.
je viens de remettre

2024-09-27 13:33 UTC, gliegard approved these changes

2024-09-30 08:53 UTC, merged