refacto readme : add pictures, etc.
IGNF/lidro pull request #27
Opened 2024-12-18 08:22 UTC by mdupaysign

Mise à jour du README en vue de la diffusion de LIDRO

2024-12-19 16:27 UTC, leavauchier reviewed
Voilà ma relecture !

2024-12-19 16:27 UTC, leavauchier commented on README.md
>  Cette modélisation des surfaces hydrographiques se décline en 3 grands enjeux :​
Typo plus haut "surfaces d'eau~x~", plusieurs fois

Pour rendre l'objectif encore, j'aurais bien envie de rajouter plus tôt l'info qu'on travaille sur des données lidar, ça pourrait donner qqc comme :

> # LIDRO (Aplanissement des surfaces d'eau pour la gnérétion de modèles numériques de terrain à partir de données Lidar)
> 
> Lidro est un outil permettant de créer ...



ou 

> # Lidro 
> Aplanissement des surfaces d'eau pour la gnérétion de modèles numériques de terrain à partir de données Lidar
> 
> Lidro est un outil permettant de créer automatiquement des points virtuels le long des surfaces d'eaux afin de créer des modèles numériques co

2024-12-19 16:27 UTC, leavauchier commented on README.md
> +* Mise en plan des grands cours d’eau (>5m large) pour assurer l’écoulement​. / ! \ Pour l'instant, seulement cette étape est développée dans LIDRO.
```suggestion
* Mise en plan des grands cours d’eau (>5m large) pour assurer l’écoulement​. **A noter : Pour l'instant, seule cette partie est développée dans LIDRO.**
```

(en gros c'est surtout que j'ai pas tant l'impression que c'est des étapes que des cas d'usage différents

2024-12-19 16:27 UTC, leavauchier commented on README.md
> +L’écoulement des eaux n’est pas toujours cohérent sur les MNT produits à partir des données LIDAR classées. On observe par exemple quelques fois des cuvettes artefacts le long de certains cours d’eau
```suggestion
L’écoulement de l'eau n’est pas toujours cohérent sur les MNT produits à partir de données LIDAR classées. On observe par exemple quelques fois des cuvettes artefacts le long de certains cours d’eau surfaciques. Le traitement mis en œuvre a pour objectif de rendre l’écoulement cohérent (selon des altitudes décroissantes) sur les cours d’eau surfaciques.
```
+ 3 remarques : 
- Ca vaut peut-être le coup de rajouter une image ici pour illustrer.
- pour le cas général dont on parle et que lidro corrige déjà , c'est aussi désigné par le nom de cuvettes ?
- tu peux peut-être expliquer pourquoi ça arrive : bas des berges pas toujours visible, quasi-absence de points sur l'eau)

D'ailleurs pourquoi surfacique ?

2024-12-19 16:27 UTC, leavauchier commented on README.md
> +- de données vectorielles représentant le réseau hydrographique issu des différentes bases de données IGN (BDUnis et/ou BDTopo : tronçons hydrographiques, etc.)
```suggestion
- de données vectorielles représentant le réseau hydrographique issu des différentes bases de données IGN (BDUni et/ou BDTopo : tronçons hydrographiques, etc.)
```

2024-12-19 16:27 UTC, leavauchier commented on README.md
> +### Process pour les grands cours d'eaux (> 5m de large)
```suggestion
### Processus pour les grands cours d'eau (> 5m de large)
```

2024-12-19 16:27 UTC, leavauchier commented on README.md
> +Le process mis en place se décompose en quatre parties :
```suggestion
Le processus mis en place se décompose en quatre parties :
```

2024-12-19 16:27 UTC, leavauchier commented on README.md
> +* 4- Création de points virtuels correspondant à une grille régulière (paramétrable) à l'intérieur des masques hydrographiques.
J'ai l'impression qu'il y a quelque chose à faire sur la mise en page pour éviter d'avoir l'impression qu'il n'y a que 2 points à cause des précisions sur l'étape 2. Peut-être que ré-organiser suffit

Par exemple comme ça : 

> * 1- Création de masques hydrographiques à l'échelle de la dalle LIDAR.
> * 2- Création de masques hydrographiques pré-filtrés à l'échelle du chantier. 
> * 3- Création automatiques des tronçons hydrographiques - les "squelettes hydrographiques" des masques hydrographiques - c'est-à-dire les lignes internes indiquant le sens de l'écoulement de l'eau.
> * 4- Création de points virtuels correspondant à une grille régulière (paramétrable) à l'intérieur des masques hydrographiques.
> 
> L'étape 2 comprend :
>   * la suppression de ces masques dans les zones ZICAD/ZIPVA : étape manuelle, à réaliser sous QGIS par exemple
>   * la suppression des ces masques en dehors des grands cours d'eau, et leurs nettoyage : étape manuelle, à réaliser sous QGIS par exemple
>   * la suppression des aires < 150 m² (paramétrable)
> 
> <img src="images/correction_manuelle_masque_hydro.jpg" alt="Contrôle et nettoyage des masques hydrographiques à l'échelle du chantier" width="800">
> 


ou 

> 
> * 1- Création de masques hydrographiques à l'échelle de la dalle LIDAR.
> 
> * 2- Création de masques hydrographiques pré-filtrés à l'échelle du chantier. 
> 
> > Cette étape comprend :
> >   * la suppression de ces masques dans les zones ZICAD/ZIPVA : étape manuelle, à réaliser sous QGIS par exemple
> >   * la suppression des ces masques en dehors des grands cours d'eau, et leurs nettoyage : étape manuelle, à réaliser sous QGIS par exemple
> >   * la suppression des aires < 150 m² (paramétrable)
> > 
> > <img src="images/correction_manuelle_masque_hydro.jpg" alt="Contrôle et nettoyage des masques hydrographiques à l'échelle du chantier" width="800">
> 
> * 3- Création automatiques des tronçons hydrographiques - les "squelettes hydrographiques" des masques hydrographiques - c'est-à-dire les lignes internes indiquant le sens de l'écoulement de l'eau.
> 
> * 4- Création de points virtuels correspondant à une grille régulière (paramétrable) à l'intérieur des masques hydrographiques.

2024-12-19 16:27 UTC, leavauchier commented on README.md
> +### Détails du process de créations des points virtuels pour les grands cours d'eaux (>5m de large)
```suggestion
### Détails du processus de création des points virtuels pour les grands cours d'eau (>5m de large)
```

2024-12-19 16:27 UTC, leavauchier commented on README.md
> +
```suggestion
* 2- Création de points virtuels nécessitant plusieurs étapes intermédiaires :
  * 2.1 Création des points virtuels 2D espacés selon une grille régulière tous les N mètres (paramétrable) à l'intérieur du masque hydrographique "écoulement"
  * 2.2 Affecter une valeur d'altitude à ces points virtuels en fonction des "Z" calculés à l'étape précédente (interpolation linéaire ou aplanissement)

```

Il manquait un espace pour que la mise en page soit prise en compte

2024-12-19 16:27 UTC, leavauchier commented on README.md
>  ```
à la ligne 103 : peut-être rajouter que les contributions sont bienvenues sous la forme de Pull requests.

2024-12-19 16:27 UTC, leavauchier commented on README.md
> +* ``` environment.yml ```: un fichier d'environnement
```suggestion
* ``` environment.yml ```: le fichier permettant de créer l'environnement conda dans lequel lidro peut être utilisé
```

2024-12-19 16:27 UTC, leavauchier commented on README.md
> +* Les dalles LIDAR classées avec leurs points virtuels (grille règluière tous les N mètre)
```suggestion
* Les dalles LIDAR classées avec leurs points virtuels (grille règluière tous les N mètres)
```

2024-12-19 16:27 UTC, leavauchier commented on README.md
> +Dans la branche ```rectify_model_under_bridge``` (https://github.com/IGNF/lidro/tree/rectify_model_under_bridge), un correctif non industriel a été développé.
```suggestion
Dans la branche ```rectify_model_under_bridge``` (https://github.com/IGNF/lidro/tree/rectify_model_under_bridge), un correctif a été développé, mais est moins abouti que le code de la branche `main` (notamment en termes de tests)
```
(je suis pas sûre qu'il faille parler d'industrialisation ici)

2024-12-19 16:27 UTC, leavauchier commented on README.md
> +D'un point de vue mathématique, cela signifie que le "Dernier point squelette AMONT < Premier point squelette AVAL = ALERTE".
```suggestion
D'un point de vue logique, cela signifie : "Si Dernier point squelette AMONT < Premier point squelette AVAL alors ALERTE". 
```

2024-12-20 15:25 UTC, mdupaysign commented on README.md
> +L’écoulement des eaux n’est pas toujours cohérent sur les MNT produits à partir des données LIDAR classées. On observe par exemple quelques fois des cuvettes artefacts le long de certains cours d’eau
C'est corrigé, et j'ai rajouté deux nouveaux exemples

2024-12-20 15:37 UTC, mdupaysign commented on README.md
> +Dans la branche ```rectify_model_under_bridge``` (https://github.com/IGNF/lidro/tree/rectify_model_under_bridge), un correctif non industriel a été développé.
yes tu as raison ;)

2025-01-06 10:54 UTC, leavauchier commented on README.md
> +Lidro est un outil permettant de créer automatiquement des points virtuels le long des surfaces d'eaux afin de créer des modèles numériques cohérents avec les modèles hydrologiques.
typo 
```suggestion
Lidro est un outil permettant de créer automatiquement des points virtuels le long des surfaces d'eau afin de créer des modèles numériques cohérents avec les modèles hydrologiques. 
```

2025-01-06 10:54 UTC, leavauchier commented on README.md
> +Par exemple dans l'image ci-dessous, le niveau d'eau en aval du barrage est supérieur à celui présent en amont.
Pour moi ce qu'on corrigeait le plus, c'était plus le fait d'avoir des cuvettes au niveau du barrage, et surtout d'avoir un niveau avec une grosse triangulation depuis des points qui sont plus haut que la berge. Là j'ai l'impression que tu parles surtout des derniers problèmes de cohérence entre les segments déjà traités qu'on a eus (et qu'on n'a pas corrigés dans la version du main)
Tu peux confirmer ?

2025-01-06 10:54 UTC, leavauchier commented on README.md
> +  * 2.2 Affecter une valeur d'altitude à ces points virtuels en fonction des "Z" calculés à l'étape précédente (interpolation linéaire ou aplanissement)
Pour être cohérent avec le point 1 :
~~Création de points~~ -> Créer des points virtuels

~~2.1 Création des points virtuels 2D~~ -> 2.1 Créer des points virtuels 2d

2025-01-06 10:54 UTC, leavauchier commented on README.md
>  Ci-dessous un AVANT/APRES de la production d'un MNT SANS les points virtuels (MNT classé) / AVEC les points vrituels (MNT optimisé).
J'ai l'impression que c'est plutôt l'image de cette partie qui mériterait d'être au début du readme plutôt que celle du barrage, ça fait plus l'effet wahou du avant/après (ou tu peux garder les 2)

2025-01-14 14:59 UTC, mdupaysign commented
Mise à jour du README en vue de la publication LINKEDIN  + Modification de input_dir = input_dir + pointcloud pour la fonction "extract_point_skeleton".

2025-01-14 15:29 UTC, leavauchier requested changes

2025-01-14 15:29 UTC, leavauchier commented on README.md
> +### 4) étapes 1. Création des points tous les N mètres le long des squelettes hydrographiques, et réccupération les N plus proches voisins points LIDAR "SOL"
typos : 
```suggestion
### 4) étape 1. Création des points tous les N mètres le long des squelettes hydrographiques, et récupération les N plus proches voisins points LIDAR "SOL"
```

2025-01-14 15:29 UTC, leavauchier commented on lidro/create_virtual_point/vectors/extract_points_around_skeleton.py
> +    input_dir_points = os.path.join(input_dir, "")
ici tu fais un join abec qqc de vide, ça parait plus intéressant d'utiliser directement `input_dir` à la place d'`input_dir_points` dans la suite, ou de changer le nom de `input_dir` pour `input_dir_points` (au moment où tu crées `input_dir`)

2025-01-14 15:59 UTC, leavauchier approved these changes

2025-01-14 16:03 UTC, merged